# Generated by Django 5.2 on 2025-05-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0004_remove_userdata_rpm_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IST_Base', models.CharField(max_length=10)),
                ('Target_Income', models.FloatField(blank=True, null=True)),
                ('Target_Sales', models.FloatField(blank=True, null=True)),
                ('Target_Team', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user', to_field='Folio_Number')),
            ],
        ),
    ]
