# Generated by Django 5.2 on 2025-05-02 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0002_rename_target_data_target_data_ist'),
        ('homeapp', '0004_remove_userdata_rpm_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_data_ist',
            name='IST_Base',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='target_data_ist',
            name='Target_Income',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target_data_ist',
            name='Target_Sales',
            field=models.FloatField(default=12550),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target_data_ist',
            name='Target_Team',
            field=models.FloatField(default=12545),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target_data_ist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user'),
        ),
    ]
