# Generated by Django 5.2 on 2025-05-02 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0003_alter_target_data_ist_ist_base_and_more'),
        ('homeapp', '0005_userdata_hp_t_24_25_userdata_hr_t_24_25_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_data_ist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user', to_field='Folio_Number'),
        ),
    ]
