# Generated by Django 5.2 on 2025-05-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0004_alter_target_data_ist_user'),
        ('homeapp', '0007_rename_rpm_23_24_userdata_team_23_24'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target_Card_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target_Income', models.FloatField()),
                ('Target_Sales', models.FloatField()),
                ('Target_Team', models.FloatField()),
                ('Target_ASM', models.FloatField()),
                ('Target_HSM', models.FloatField()),
                ('Target_RPM', models.FloatField()),
                ('Target_DTR', models.FloatField()),
                ('Target_NID', models.FloatField()),
                ('Target_NGL', models.FloatField()),
                ('Target_VV', models.FloatField()),
                ('Target_OBS', models.FloatField()),
                ('Target_AD', models.FloatField()),
                ('TEL_Target', models.FloatField()),
                ('UP_Target', models.FloatField()),
                ('RJ_Target', models.FloatField()),
                ('PB_Target', models.FloatField()),
                ('HR_Target', models.FloatField()),
                ('HP_Target', models.FloatField()),
                ('Target_BO', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user', to_field='Folio_Number')),
            ],
        ),
    ]
