# Generated by Django 5.2 on 2025-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0006_target_card_data_ik_target_card_data_pp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_card_data',
            name='TURPHH_Target',
            field=models.FloatField(default=101),
            preserve_default=False,
        ),
    ]
