# Generated by Django 5.2 on 2025-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0007_target_card_data_turphh_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_card_data',
            name='CMR_Centre_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='CMR_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='HP_BO_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='HR_BO_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='Mahavir_Award_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='PB_BO_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='RJ_BO_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='Star_NGL_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='TAL_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='TEL_BO_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='TURPHH_BO_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='UP_BO_Target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
