# Generated by Django 5.2 on 2025-05-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0008_target_card_data_cmr_centre_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_data_ist',
            name='agriculture_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_data_ist',
            name='ayurman_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_data_ist',
            name='paridhan_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_data_ist',
            name='swastham_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
