# Generated by Django 5.2 on 2025-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0009_target_data_ist_agriculture_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target_data_ist',
            name='agriculture_percent',
        ),
        migrations.RemoveField(
            model_name='target_data_ist',
            name='ayurman_percent',
        ),
        migrations.RemoveField(
            model_name='target_data_ist',
            name='paridhan_percent',
        ),
        migrations.RemoveField(
            model_name='target_data_ist',
            name='swastham_percent',
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='agriculture_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='ayurman_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='paridhan_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='swastham_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
