# Generated by Django 5.2 on 2025-05-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0010_remove_target_data_ist_agriculture_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target_card_data',
            name='Target_ASM',
        ),
        migrations.RemoveField(
            model_name='target_card_data',
            name='Target_HSM',
        ),
    ]
