# Generated by Django 5.2 on 2025-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0011_remove_target_card_data_target_asm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_card_data',
            name='Target_AGR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='Target_AYU',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='Target_Par',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target_card_data',
            name='Target_SWA',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
