# Generated by Django 5.2 on 2025-05-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0012_target_card_data_target_agr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target_card_data',
            old_name='Target_Par',
            new_name='Target_PAR',
        ),
    ]
