# Generated by Django 5.2 on 2025-05-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0013_rename_target_par_target_card_data_target_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_card_data',
            name='Target_Team1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
