# Generated by Django 5.2 on 2025-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0015_target_card_data_target_kv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_card_data',
            name='Target_BO',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
