# Generated by Django 5.2 on 2025-05-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=20)),
                ('Rank', models.CharField(max_length=50)),
                ('Folio_Number', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('GLS_4_Participation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GLS_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=20)),
                ('Seat_Number', models.CharField(max_length=10)),
                ('Checked_In', models.CharField(max_length=3)),
                ('Logged_In', models.CharField(max_length=3)),
                ('Feedback_Form_Filled', models.CharField(max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user', to_field='Folio_Number')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income_Total', models.FloatField()),
                ('Sales_Total', models.FloatField()),
                ('Team_Total', models.FloatField()),
                ('RPM_Total', models.FloatField()),
                ('Income_24_25', models.FloatField()),
                ('Sales_24_25', models.FloatField()),
                ('Team_24_25', models.FloatField()),
                ('RPM_24_25', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user', to_field='Folio_Number')),
            ],
        ),
    ]
