# Generated by Django 5.2 on 2025-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gls_data',
            name='Checked_In',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gls_data',
            name='Feedback_Form_Filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gls_data',
            name='Logged_In',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='GLS_4_Participation',
            field=models.BooleanField(default=False),
        ),
    ]
