# Generated by Django 5.2 on 2025-05-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_gls_data_checked_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Income_Total',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='Sales_Total',
        ),
    ]
