# Generated by Django 5.2 on 2025-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_remove_userdata_rpm_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='HP_T_24_25',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='HR_T_24_25',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='PB_T_24_25',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='RJ_T_24_25',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='TEL_T_24_25',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='UP_T_24_25',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
