# Generated by Django 5.2 on 2025-05-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_userdata_rpm_23_24'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='RPM_23_24',
            new_name='Team_23_24',
        ),
    ]
