# Generated by Django 5.2 on 2025-05-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_rename_rpm_23_24_userdata_team_23_24'),
    ]

    operations = [
        migrations.AddField(
            model_name='gls_data',
            name='Checkin_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
