# Generated by Django 5.2 on 2025-05-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_gls_data_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gls_data',
            name='Expected_Arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gls_data',
            name='First_Time_Attendee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gls_data',
            name='Terms_Agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gls_data',
            name='Terms_Read',
            field=models.BooleanField(default=False),
        ),
    ]
