# Generated by Django 5.2 on 2025-05-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_gls_data_expected_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gls_data',
            name='Admit',
            field=models.BooleanField(default=False),
        ),
    ]
