# Generated by Django 5.2 on 2025-05-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_gls_data_admit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gls_data',
            name='Terms_Read',
        ),
    ]
