# Generated by Django 5.2 on 2025-05-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_remove_gls_data_terms_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gls_data',
            name='Terms_Agreed',
        ),
        migrations.AddField(
            model_name='gls_data',
            name='Emergency_Contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='gls_data',
            name='Mode_of_Transport',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
