# Generated by Django 5.2 on 2025-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_remove_gls_data_terms_agreed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gls_data',
            name='Emergency_Contact',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
