# Generated by Django 5.2 on 2025-05-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_alter_gls_data_emergency_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Team_Total',
        ),
    ]
