# Generated by Django 5.2 on 2025-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_remove_userdata_team_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='TC_Filled',
            field=models.BooleanField(default=False),
        ),
    ]
