# Generated by Django 5.2 on 2025-05-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_user_tc_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TC_Filled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
